name: pytorch16
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.10.14=0
  - certifi=2020.11.8=py36h06a4308_0
  - cloudpickle=1.6.0=py_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py36h7b6447c_0
  - dask-core=2.30.0=py_0
  - decorator=4.4.2=py_0
  - freetype=2.10.2=h5ab3b9f_0
  - h5py=2.10.0=py36hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - imageio=2.9.0=py_0
  - intel-openmp=2020.2=254
  - joblib=0.17.0=py_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.2.0=py36hdb11119_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.2=heb0550a_3
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py36h5ffbc53_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.2.0=py36h23d657b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.5=py_0
  - ninja=1.10.1=py36hfd86e86_0
  - numpy=1.19.1=py36hbc911f0_0
  - numpy-base=1.19.1=py36hfa32c7d_0
  - olefile=0.46=py36_0
  - openssl=1.1.1h=h7b6447c_0
  - pillow=7.2.0=py36hb39fc2d_0
  - pip=20.2.3=py36_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.6.12=hcff3b4d_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.6.0=py3.6_cuda10.2.89_cudnn7.6.5_0
  - pywavelets=1.1.1=py36h7b6447c_2
  - pyyaml=5.3.1=py36h7b6447c_1
  - readline=8.0=h7b6447c_0
  - scikit-image=0.16.2=py36h0573a6f_0
  - scikit-learn=0.23.2=py36h0573a6f_0
  - scipy=1.5.2=py36h0b6359f_0
  - setuptools=50.3.0=py36hb0f4dca_1
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.11.1=py_0
  - torchvision=0.7.0=py36_cu102
  - tornado=6.0.4=py36h8c4c3a4_1
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.13.0
    - alpha-transform==0.0.1
    - antialiased-cnns==0.3
    - astropy==4.0.1.post1
    - cachetools==4.2.2
    - chardet==4.0.0
    - dataclasses==0.8
    - einops==0.3.0
    - future==0.18.2
    - google-auth==1.32.1
    - google-auth-oauthlib==0.4.4
    - grpcio==1.38.1
    - healpy==1.14.0
    - idna==2.10
    - importlib-metadata==4.6.1
    - kornia==0.4.0
    - markdown==3.3.4
    - mat73==0.46
    - numexpr==2.7.1
    - oauthlib==3.1.1
    - opencv-python==4.4.0.44
    - pandas==1.1.3
    - protobuf==3.17.3
    - ptflops==0.6.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydicom==2.1.1
    - pyfftw==0.12.0
    - pytz==2020.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - simpleitk==2.0.2
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - torch-radon==1.0.0
    - tqdm==4.50.2
    - typing-extensions==3.10.0.0
    - urllib3==1.26.6
    - werkzeug==2.0.1
    - zipp==3.5.0
prefix: /home/xxx/anaconda3/envs/pytorch16
